apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  namespace: webapp
  labels:
    app: nginx
    monitoring: "true"
spec:
  selector:
    app: nginx
  ports:
  - name: metrics
    port: 9113
    targetPort: 9113

