apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "65.3.1"
    helm:
      releaseName: monitoring
      valueFiles:
        - $values/monitoring/kube-prometheus-stack-values.yaml
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "65.3.1"
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/monitoring/kube-prometheus-stack-values.yaml
    - repoURL: https://github.com/SkanderKaraa/k3s-gitops-stage.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
