apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-app
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitops-stage
spec:
  project: default
  source:
    repoURL: https://github.com/SkanderKaraa/k3s-gitops-stage.git
    targetRevision: main
    path: velero
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: false       # Ne pas supprimer les ressources Velero automatiquement
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

